/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取项目列表
         * @description 获取所有项目，支持分页和按名称搜索
         */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                    /** @description 搜索关键词（按名称模糊搜索） */
                    keyword?: string;
                    /** @description 按分类筛选 */
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建项目
         * @description 创建新项目
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取项目详情
         * @description 获取单个项目的详细信息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目ID */
                    projectId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description 项目不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * 更新项目信息
         * @description 更新项目的名称、描述等信息
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目ID */
                    projectId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description 项目不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * 删除项目
         * @description 删除项目（软删除），级联删除下属所有目标和约束
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目ID */
                    projectId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 项目不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取项目所有约束
         * @description 获取附加在该项目上的所有约束
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目ID */
                    projectId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConstraintListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取目标列表
         * @description 获取目标列表，可按项目筛选，按优先级排序
         */
        get: {
            parameters: {
                query?: {
                    /** @description 按项目ID筛选 */
                    project_id?: number;
                    /** @description 按完成状态筛选 */
                    is_completed?: boolean;
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建目标
         * @description 创建新目标，必须关联项目
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGoalRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取目标详情
         * @description 获取单个目标的详细信息，包含所有约束
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 目标ID */
                    goalId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalDetailResponse"];
                    };
                };
                /** @description 目标不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * 更新目标信息
         * @description 更新目标的名称、描述等信息
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 目标ID */
                    goalId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGoalRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalResponse"];
                    };
                };
                /** @description 目标不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * 删除目标
         * @description 删除目标（软删除），级联删除下属所有约束
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 目标ID */
                    goalId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 目标不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/toggle-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 切换目标完成状态
         * @description 标记目标为完成或未完成
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 目标ID */
                    goalId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 是否完成 */
                        is_completed: boolean;
                    };
                };
            };
            responses: {
                /** @description 操作成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalResponse"];
                    };
                };
                /** @description 目标不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/batch-move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量移动目标
         * @description 将多个目标批量移动到另一个项目
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchMoveGoalsRequest"];
                };
            };
            responses: {
                /** @description 移动成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            /** @description 成功移动数量 */
                            moved_count?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加约束
         * @description 添加约束到所有者（项目或目标）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConstraintRequest"];
                };
            };
            responses: {
                /** @description 添加成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConstraintResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constraints/{constraintId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新约束参数
         * @description 更新约束的参数信息
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 约束ID */
                    constraintId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateConstraintRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConstraintResponse"];
                    };
                };
                /** @description 约束不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * 删除约束
         * @description 删除约束
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 约束ID */
                    constraintId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 约束不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constraints/{ownerType}/{ownerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有者的所有约束
         * @description 获取附加在指定所有者（项目或目标）上的所有约束
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 所有者类型 */
                    ownerType: "project" | "goal";
                    /** @description 所有者ID */
                    ownerId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConstraintListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** @description 项目ID */
            project_id: number;
            /** @description 项目名称 */
            name: string;
            /** @description 项目描述 */
            description?: string | null;
            /** @description 项目分类 */
            category?: string | null;
            /**
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
            /**
             * @description 软删除标记
             * @enum {integer}
             */
            is_deleted?: 0 | 1;
        };
        CreateProjectRequest: {
            /** @description 项目名称 */
            name: string;
            /** @description 项目描述 */
            description?: string | null;
            /** @description 项目分类 */
            category?: string | null;
        };
        UpdateProjectRequest: {
            /** @description 项目名称 */
            name?: string;
            /** @description 项目描述 */
            description?: string | null;
            /** @description 项目分类 */
            category?: string | null;
        };
        ProjectResponse: {
            /** @description 请求是否成功 */
            success?: boolean;
            data?: components["schemas"]["Project"];
        };
        ProjectListResponse: {
            success?: boolean;
            data?: {
                list?: components["schemas"]["Project"][];
                total?: number;
                page?: number;
                total_pages?: number;
            };
        };
        Goal: {
            /** @description 目标ID */
            goal_id: number;
            /** @description 所属项目ID */
            project_id: number;
            /** @description 目标名称 */
            name: string;
            /** @description 目标描述 */
            description?: string | null;
            /**
             * @description 是否完成
             * @enum {integer}
             */
            is_completed?: 0 | 1;
            /**
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
            /**
             * @description 软删除标记
             * @enum {integer}
             */
            is_deleted?: 0 | 1;
        };
        CreateGoalRequest: {
            /** @description 所属项目ID */
            project_id: number;
            /** @description 目标名称 */
            name: string;
            /** @description 目标描述 */
            description?: string | null;
        };
        UpdateGoalRequest: {
            /** @description 目标名称 */
            name?: string;
            /** @description 目标描述 */
            description?: string | null;
        };
        GoalResponse: {
            success?: boolean;
            data?: components["schemas"]["Goal"];
        };
        GoalDetailResponse: {
            success?: boolean;
            data?: {
                goal?: components["schemas"]["Goal"];
                constraints?: components["schemas"]["Constraint"][];
            };
        };
        GoalListResponse: {
            success?: boolean;
            data?: {
                list?: components["schemas"]["Goal"][];
                total?: number;
                page?: number;
                total_pages?: number;
            };
        };
        BatchMoveGoalsRequest: {
            /** @description 要移动的目标ID列表 */
            goal_ids: number[];
            /** @description 目标项目ID */
            target_project_id: number;
        };
        Constraint: {
            /** @description 约束ID */
            constraint_id: number;
            /**
             * @description 所有者类型
             * @enum {string}
             */
            owner_type: "project" | "goal";
            /** @description 所有者ID */
            owner_id: number;
            /** @description 约束名称 */
            constraint_name?: string | null;
            /** @description 约束参数（JSON格式，类型不同结构不同） */
            params: Record<string, never>;
            /**
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
            /**
             * @description 软删除标记
             * @enum {integer}
             */
            is_deleted?: 0 | 1;
        };
        CreateConstraintRequest: {
            /**
             * @description 所有者类型
             * @enum {string}
             */
            owner_type: "project" | "goal";
            /** @description 所有者ID */
            owner_id: number;
            /** @description 约束名称 */
            constraint_name?: string | null;
            /** @description 约束参数 */
            params: Record<string, never>;
        };
        UpdateConstraintRequest: {
            /** @description 约束名称 */
            constraint_name?: string | null;
            /** @description 约束参数 */
            params?: Record<string, never>;
        };
        ConstraintResponse: {
            success?: boolean;
            data?: components["schemas"]["Constraint"];
        };
        ConstraintListResponse: {
            success?: boolean;
            data?: components["schemas"]["Constraint"][];
        };
        ConstraintCheckResult: {
            constraint_id?: number;
            constraint_name?: string | null;
            satisfied?: boolean;
            /** @description 不满足时的说明 */
            message?: string | null;
        };
        ConstraintCheckResponse: {
            success?: boolean;
            data?: {
                /** @description 所有约束是否都满足 */
                all_satisfied?: boolean;
                results?: components["schemas"]["ConstraintCheckResult"][];
            };
        };
        Error: {
            /** @default false */
            success: boolean;
            /** @description 错误信息 */
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
